databases:
  - name: workout-vistula
    databaseName: workout_vistula
    user: user
    plan: free

services:
  - type: web
    name: workout-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workout-vistula
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default